# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1576, 1025)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.UI_start_time = QtWidgets.QDateTimeEdit(parent=self.groupBox)
        self.UI_start_time.setCalendarPopup(True)
        self.UI_start_time.setObjectName("UI_start_time")
        self.horizontalLayout.addWidget(self.UI_start_time)
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.UI_end_time = QtWidgets.QDateTimeEdit(parent=self.groupBox)
        self.UI_end_time.setDateTime(QtCore.QDateTime(QtCore.QDate(3000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.UI_end_time.setCalendarPopup(True)
        self.UI_end_time.setObjectName("UI_end_time")
        self.horizontalLayout.addWidget(self.UI_end_time)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.UI_other_flg = QtWidgets.QCheckBox(parent=self.groupBox)
        self.UI_other_flg.setObjectName("UI_other_flg")
        self.horizontalLayout.addWidget(self.UI_other_flg)
        self.UI_search_btn = QtWidgets.QPushButton(parent=self.groupBox)
        self.UI_search_btn.setObjectName("UI_search_btn")
        self.horizontalLayout.addWidget(self.UI_search_btn)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UI_table_data = QtWidgets.QTableWidget(parent=self.tab)
        self.UI_table_data.setObjectName("UI_table_data")
        self.UI_table_data.setColumnCount(0)
        self.UI_table_data.setRowCount(0)
        self.verticalLayout.addWidget(self.UI_table_data)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "开始时间"))
        self.label_2.setText(_translate("Dialog", "结束时间"))
        self.UI_other_flg.setText(_translate("Dialog", "心跳/校时"))
        self.UI_search_btn.setText(_translate("Dialog", "搜索"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "表格数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "曲线数据"))
