# Form implementation generated from reading ui file 'log_in_UI.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(368, 289)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.UI_stauts = QtWidgets.QTextBrowser(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.UI_stauts.setFont(font)
        self.UI_stauts.setObjectName("UI_stauts")
        self.verticalLayout.addWidget(self.UI_stauts)
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.UI_usr_btn = QtWidgets.QLineEdit(parent=self.splitter)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UI_usr_btn.setFont(font)
        self.UI_usr_btn.setObjectName("UI_usr_btn")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(parent=Dialog)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_2 = QtWidgets.QLabel(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.UI_passwd_btn = QtWidgets.QLineEdit(parent=self.splitter_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UI_passwd_btn.setFont(font)
        self.UI_passwd_btn.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.UI_passwd_btn.setObjectName("UI_passwd_btn")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(parent=Dialog)
        self.splitter_3.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.UI_login_btn = QtWidgets.QPushButton(parent=self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UI_login_btn.setFont(font)
        self.UI_login_btn.setObjectName("UI_login_btn")
        self.UI_cancel_btn = QtWidgets.QPushButton(parent=self.splitter_3)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.UI_cancel_btn.setFont(font)
        self.UI_cancel_btn.setObjectName("UI_cancel_btn")
        self.verticalLayout.addWidget(self.splitter_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "用户登录"))
        self.label.setText(_translate("Dialog", "用户名"))
        self.label_2.setText(_translate("Dialog", "密码"))
        self.UI_login_btn.setText(_translate("Dialog", "登录"))
        self.UI_cancel_btn.setText(_translate("Dialog", "取消"))
