# Form implementation generated from reading ui file 'more_add_ui.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 71)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.UI_more_add_btn = QtWidgets.QPushButton(parent=Dialog)
        self.UI_more_add_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.UI_more_add_btn.setObjectName("UI_more_add_btn")
        self.gridLayout.addWidget(self.UI_more_add_btn, 1, 1, 1, 1)
        self.UI_more_path_btn = QtWidgets.QPushButton(parent=Dialog)
        self.UI_more_path_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.UI_more_path_btn.setObjectName("UI_more_path_btn")
        self.gridLayout.addWidget(self.UI_more_path_btn, 1, 0, 1, 1)
        self.UI_cancel_btn = QtWidgets.QPushButton(parent=Dialog)
        self.UI_cancel_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.UI_cancel_btn.setObjectName("UI_cancel_btn")
        self.gridLayout.addWidget(self.UI_cancel_btn, 1, 2, 1, 1)
        self.splitter = QtWidgets.QSplitter(parent=Dialog)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label = QtWidgets.QLabel(parent=self.splitter)
        self.label.setObjectName("label")
        self.UI_more_path_lineedit = QtWidgets.QLineEdit(parent=self.splitter)
        self.UI_more_path_lineedit.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.UI_more_path_lineedit.setObjectName("UI_more_path_lineedit")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "多设备导入"))
        self.UI_more_add_btn.setText(_translate("Dialog", "开始导入"))
        self.UI_more_path_btn.setText(_translate("Dialog", "选择路径"))
        self.UI_cancel_btn.setText(_translate("Dialog", "取消"))
        self.label.setText(_translate("Dialog", "文件路径："))
